# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4750c38f-ce0c-4a1f-985d-52ab0f8bdd02";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-e199fa98-bc22-41ea-b468-a4d328ed6a4b".device = "/dev/disk/by-uuid/e199fa98-bc22-41ea-b468-a4d328ed6a4b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B47C-B46B";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/84a98f6b-9eb2-4fbc-b1d0-e2195353e5b0";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-14245c41-e4c4-4266-accc-407570116c37".device = "/dev/disk/by-uuid/14245c41-e4c4-4266-accc-407570116c37";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0ea992dd-90da-49ce-8908-65daa1005653"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
