bind=SUPER+SHIFT,E,quit
bind=SUPER+SHIFT,R,reload_config
bind=Alt,F4,killclient

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+Shift,1,tag,1,0
bind=SUPER+Shift,2,tag,2,0
bind=SUPER+Shift,3,tag,3,0
bind=SUPER+Shift,4,tag,4,0
bind=SUPER+Shift,5,tag,5,0
bind=SUPER+Shift,6,tag,6,0
bind=SUPER+Shift,7,tag,7,0
bind=SUPER+Shift,8,tag,8,0
bind=SUPER+Shift,9,tag,9,0

bind=SUPER,O,toggleoverview

bind=SUPER,D,toggle_named_scratchpad,Beeper,Beeper,fish -c beeper
bind=Ctrl+Shift,Escape,toggle_named_scratchpad,Sysmon,Sysmon,alacritty --class "Sysmon" -T "Sysmon" -e "btop"

#gesturebind=none,up,4,toggleoverview
#gesturebind=none,down,4,toggleoverview

gesturebind=none,down,3,viewtoleft
gesturebind=none,up,3,viewtoright
