exec-once=dms run

trackpad_natural_scrolling=1

tag_animation_direction=0

tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

windowrule=isnamedstratchpad:1,appid:Beeper,title:Beeper
windowrule=isnamedstratchpad:1,appid:Sysmon,title:Sysmon
